import { useMemo, useState } from 'react'
import EmptyState from './EmptyState'
import ConfirmDialog from './ConfirmDialog'
import { fallback, formatDate, formatValue } from '../utils/formatters'

const friendlySteps = { supabase_insert_order:'שמירת הזמנה למסד הנתונים', openai_parse_order:'פענוח הזמנה עם AI', json_parse_or_create:'עיבוד מבנה הנתונים', gmail_update_label:"עדכון תווית בג'ימייל", call_order_json_handler_webhook:'שליחה לאוטומציית עיבוד ההזמנה' }
export default function ErrorsPanel({ logs, onMarkSeen, onDelete }) {
  const errors = useMemo(() => logs.filter((l) => ['error','handled'].includes(String(l.status).toLowerCase())), [logs])
  const unresolvedCount = errors.filter((l) => String(l.status).toLowerCase() === 'error').length
  const [query,setQuery] = useState(''), [scenario,setScenario] = useState('all'), [step,setStep] = useState('all'), [statusFilter,setStatusFilter] = useState('open'), [selected,setSelected] = useState(null), [confirmation,setConfirmation] = useState(null), [action,setAction] = useState(''), [actionError,setActionError] = useState('')
  const scenarios = [...new Set(errors.map((l) => l.scenario_name).filter(Boolean))], steps = [...new Set(errors.map((l) => l.step_name).filter(Boolean))]
  const shown = errors.filter((l) => (statusFilter === 'all' || (statusFilter === 'open' ? String(l.status).toLowerCase() === 'error' : String(l.status).toLowerCase() === 'handled')) && (scenario === 'all' || l.scenario_name === scenario) && (step === 'all' || l.step_name === step) && (!query || `${l.email_id || ''} ${l.error_message || ''}`.toLowerCase().includes(query.toLowerCase())))
  async function confirmAction() { if (!confirmation) return; const {type,log}=confirmation; setAction(`${type}:${log.id}`); setActionError(''); try { if(type==='seen') await onMarkSeen(log); else { await onDelete(log); if(selected?.id===log.id)setSelected(null) } setConfirmation(null) } catch { setActionError(type==='seen'?'לא ניתן לסמן את השגיאה כרגע. נסו שוב.':'לא ניתן למחוק את השגיאה כרגע. נסו שוב.') } finally { setAction('') } }
  return <section className="panel errors-panel"><div className="view-heading"><div><h2>שגיאות אוטומציה</h2><p>תקלות שדורשות תשומת לב</p></div><span className="count-pill">{unresolvedCount}</span></div>
    <div className="filters errors-filters"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="חיפוש לפי מזהה מייל או הודעת שגיאה..." /><select value={scenario} onChange={(e) => setScenario(e.target.value)}><option value="all">כל התרחישים</option>{scenarios.map((x) => <option value={x} key={x}>{x}</option>)}</select><select value={step} onChange={(e) => setStep(e.target.value)}><option value="all">כל השלבים</option>{steps.map((x) => <option value={x} key={x}>{friendlySteps[x] || x}</option>)}</select><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="open">לא טופלו</option><option value="handled">טופלו</option><option value="all">הכל</option></select></div>
    {!shown.length ? <EmptyState>אין שגיאות התואמות לסינון.</EmptyState> : <div className="error-list">{shown.map((log,i) => { const handled=String(log.status).toLowerCase()==='handled', busy=action.endsWith(`:${log.id}`); return <article className={`error-item${handled?' error-item--handled':''}`} key={log.id ?? i}><div className="error-item__top"><div><strong>{fallback(log.scenario_name)}</strong><span>{friendlySteps[log.step_name] || fallback(log.step_name)}</span>{handled && <span className="badge badge--handled">טופל</span>}</div><time>{formatDate(log.created_at)}</time></div><p>{fallback(log.error_message)}</p>{log.email_id && <small dir="ltr">Email ID: {log.email_id}</small>}<div className="error-actions"><button className="button button--secondary technical-button" disabled={busy} onClick={() => setSelected(log)}>פרטים טכניים</button>{!handled && <button className="button button--secondary technical-button" disabled={busy} onClick={() => {setActionError('');setConfirmation({type:'seen',log})}}>סמן כנראה</button>}<button className="button button--delete technical-button" disabled={busy} onClick={() => {setActionError('');setConfirmation({type:'delete',log})}}>מחק</button></div></article>})}</div>}
    {selected && <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && setSelected(null)}><section className="modal technical-modal"><header className="modal__header"><div><p className="eyebrow">פרטים טכניים</p><h2>{friendlySteps[selected.step_name] || selected.step_name}</h2></div><button className="icon-button" onClick={() => setSelected(null)}>×</button></header><h3>מטען גולמי</h3><pre>{formatValue(selected.raw_payload)}</pre><h3>רשומת לוג מלאה</h3><pre>{formatValue(selected)}</pre></section></div>}
    <ConfirmDialog open={Boolean(confirmation)} title={confirmation?.type==='seen'?'סימון שגיאה כנראתה':'מחיקת שגיאת אוטומציה'} message={confirmation?.type==='seen'?'האם לסמן את השגיאה הזו כנראתה? היא לא תופיע יותר בספירת השגיאות הפתוחות.':'האם למחוק את השגיאה הזו לצמיתות?'} confirmText={confirmation?.type==='seen'?'סמן כנראה':'מחק'} danger={confirmation?.type==='delete'} loading={Boolean(action)} loadingText={confirmation?.type==='delete'?'מוחק...':'שומר...'} error={actionError} onConfirm={confirmAction} onCancel={() => {setConfirmation(null);setActionError('')}} />
  </section>
}
